---
- name: Simple AWX Git Test
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ping localhost
      ansible.builtin.ping:

    - name: Create a sample file
      ansible.builtin.file:
        path: /tmp/awx_git_test.txt
        state: touch
    - name: Check the update
      ansible.builtin.command: cat /proc/uptime
      
